[WIP] Inject store arguments in Behat hooks non step methods
gorghoa/ScenarioStateBehatExtension pull request #24
Opened 2017-04-04 08:27 UTC by vincentchalamon

Fix #23

2017-04-04 09:39 UTC, gorghoa reviewed
thanks @vincentchalamon, this is very nice work 👍

2017-04-04 09:39 UTC, gorghoa commented on src/ScenarioStateCall.php
> +        $errorReportingLevel;
I don’t quite see the point of those expressions 🤔

2017-04-04 09:39 UTC, vincentchalamon commented on src/ScenarioStateCall.php
> +        $errorReportingLevel;
Hey, it's still WIP ;)

2017-04-24 20:53 UTC, vincentchalamon commented
Unit tests in progress…

2017-04-25 15:27 UTC, meyerbaptiste requested changes

2017-04-25 15:27 UTC, meyerbaptiste commented on src/Hook/Dispatcher/ScenarioStateHookDispatcher.php
> +        $results = array();
Use short syntax!

2017-04-25 15:27 UTC, meyerbaptiste commented on src/Hook/Dispatcher/ScenarioStateHookDispatcher.php
> +            $paramsKeys = array_map(function($element) {
What about `foreach` vs `array_map()`?

2017-04-25 15:27 UTC, meyerbaptiste commented on src/Hook/Tester/ScenarioStateHookableScenarioTester.php
> +        $hookCallResults = $this->dispatcher->dispatchScopeHooks(new BeforeScenarioScope($env, $feature, $scenario));
This var is useless.

2017-04-25 15:27 UTC, meyerbaptiste commented on src/Hook/Tester/ScenarioStateHookableScenarioTester.php
> +        $hookCallResults = $this->dispatcher->dispatchScopeHooks(new AfterScenarioScope($env, $feature, $scenario, $result));
This var is useless.

2017-04-25 21:23 UTC, vincentchalamon commented
Scrutinizer patches are wrong: http://www.php-fig.org/psr/psr-2/#closures
Some Scrutinizer issues are wrong (duplicate code, PHPUnit mocks), but the other issues should be fixed in another PR (https://goo.gl/cA4uEC)

2017-04-26 15:15 UTC, gorghoa approved these changes
Nice :) 👍

2017-04-26 15:33 UTC, gorghoa commented
@meyerbaptiste, ok for you?

2017-04-26 15:35 UTC, gorghoa commented
@gregcop1, If you have some time to spend, could you verify that the PR fixes your use case? (If not, just trust @vincentchalamon’s work and all will be fine I’m sure)

2017-04-26 15:39 UTC, gorghoa commented
Note. I’m okay with the small BC breaks due to namespace reorganization (the `Exception` chiefly).

I’m aware it conflicts with semver, but I expect no one will feel the pain since it’s deeply internal subject and the still small user base ;)

2017-04-26 15:42 UTC, meyerbaptiste approved these changes

2017-04-26 15:46 UTC, merged